name: Notify Iteration Start

on:
  workflow_call:
    inputs:
      notify_type:
        required: true
        type: string
      slack_webhook:
        required: false
        type: string
      discord_webhook:
        required: false
        type: string
      notify_email:
        required: false
        type: string
      custom_message:
        required: false
        type: string
      custom_title:
        required: false
        type: string
      assignee_name:
        required: false
        type: string
      project_url:
        required: false
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get Today Date
        id: date
        run: echo "today=$(date -I)" >> $GITHUB_OUTPUT

      - name: Set Defaults
        id: defaults
        run: |
          echo "msg_title=${{ inputs.custom_title || '🚀 New Iteration Started' }}" >> $GITHUB_OUTPUT
          echo "msg_body=${{ inputs.custom_message || format('Hi {0},\nPlease check the project board: {1}', inputs.assignee_name || 'team', inputs.project_url || '[Project Board]') }}" >> $GITHUB_OUTPUT

      - name: Set Slack Webhook Fallback
        if: inputs.notify_type == 'slack'
        run: |
          echo "SLACK_WEBHOOK=${{ inputs.slack_webhook || secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV

      - name: Notify via GitHub Issue
        if: inputs.notify_type == 'github'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const assignee = '${{ inputs.assignee_name || 'team' }}';
            const projectUrl = '${{ inputs.project_url || 'https://github.com/orgs/YOUR_ORG/projects' }}';
            const body = `${{ inputs.custom_message || '' }}\n\n👤 *Assigned to:* ${assignee}\n📎 ${projectUrl}\n📅 Date: ${new Date().toDateString()}`;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `${{ inputs.custom_title || '🚀 New Iteration Started' }}`,
              body,
              labels: ['iteration']
            });

      - name: Notify via Slack
        if: inputs.notify_type == 'slack'
        run: |
         : "${{ inputs.project_url || 'https://github.com/orgs/YOUR_ORG/projects' }}"  # ensure not empty
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "${{ inputs.custom_title || '🚀 New Iteration Started' }}",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "👤 *Assigned to:* ${{ inputs.assignee_name || 'team' }}\n📎 ${{ inputs.project_url || 'Project Board' }}\n📅 *Date:* $(date -I)\n\n${{ inputs.custom_message || 'Please check the project board for updated tasks.' }}"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "Stay focused and ship something awesome! 🔥"
                  }
                ]
              }
            ]
          }' \
          "$SLACK_WEBHOOK"

      - name: Notify via Discord
        if: inputs.notify_type == 'discord'
        run: |
          curl -H "Content-Type: application/json" \
          -X POST -d "{\"content\": \"${{ inputs.custom_title || '🚀 New Iteration Started' }}\\n👤 Assigned to: ${{ inputs.assignee_name || 'team' }}\\n📎 ${{ inputs.project_url || 'Project Board' }}\\n📅 Date: $(date -I)\\n${{ inputs.custom_message || 'Please check the project board for updated tasks.' }}\"}" \
          ${{ inputs.discord_webhook }}

      - name: Notify via Email (Mailgun Example)
        if: inputs.notify_type == 'email'
        run: |
          curl -s --user "api:${{ secrets.MAILGUN_API_KEY }}" \
          https://api.mailgun.net/v3/YOUR_DOMAIN/messages \
          -F from='Notifier <notifier@YOUR_DOMAIN>' \
          -F to=${{ inputs.notify_email }} \
          -F subject="${{ inputs.custom_title || '🚀 New Iteration Started' }}" \
          -F text="👤 Assigned to: ${{ inputs.assignee_name || 'team' }}\n📎 ${{ inputs.project_url || 'Project Board' }}\n📅 Date: $(date -I)\n${{ inputs.custom_message || 'Please check the GitHub Project board. New sprint begins today.' }}"
